In [1]:
"""Notebook consisting of an analysis of imperfect data
   in Seattle and NOAA data sets.
"""

'Notebook consisting of an analysis of imperfect data\n   in Seattle and NOAA data sets.\n'

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [30]:
NOAA = pd.read_csv("NOAA_data.csv")

In [31]:
#  Need to format the Date to match the fremont dates
NOAA['DATE'] = pd.to_datetime(NOAA['DATE'].astype(str))

In [32]:
NOAA.rename(columns={'DATE': 'Date'}, inplace=True)

In [33]:
NOAA.set_index('Date')

,STATION,STATION_NAME,PRCP,SNWD,SNOW,WESF
Date,,,,,,
2013-01-01,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2013-01-02,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2013-01-03,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2013-01-04,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.27,-9999.0,-9999.0,-9999.0
2013-01-05,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,-9999.0,-9999.0
2013-01-06,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.07,-9999.0,-9999.0,-9999.0
2013-01-07,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.07,-9999.0,-9999.0,-9999.0
2013-01-08,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.04,-9999.0,-9999.0,-9999.0
2013-01-09,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.84,-9999.0,-9999.0,-9999.0
2013-01-10,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.24,-9999.0,-9999.0,-9999.0
2013-01-11,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.04,-9999.0,-9999.0,-9999.0
2013-01-12,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2013-01-13,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2013-01-14,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2013-01-15,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2013-01-16,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2013-01-17,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2013-01-18,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2013-01-19,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2013-01-20,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2013-01-21,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2013-01-22,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2013-01-23,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2013-01-24,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.31,-9999.0,-9999.0,-9999.0
2013-01-25,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.19,-9999.0,-9999.0,-9999.0
2013-01-26,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.18,-9999.0,-9999.0,-9999.0
2013-01-27,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.09,-9999.0,-9999.0,-9999.0
2013-01-28,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.04,-9999.0,-9999.0,-9999.0
2013-01-29,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.33,-9999.0,-9999.0,-9999.0
2013-01-30,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.45,-9999.0,-9999.0,-9999.0
...,...,...,...,...,...,...
2015-03-28,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.01,-9999.0,-9999.0,-9999.0
2015-03-29,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,-9999.0,-9999.0
2015-03-30,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2015-03-31,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.06,-9999.0,-9999.0,-9999.0
2015-04-01,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.17,-9999.0,-9999.0,-9999.0
2015-04-02,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.19,-9999.0,-9999.0,-9999.0
2015-04-03,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.01,-9999.0,-9999.0,-9999.0
2015-04-04,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.02,-9999.0,-9999.0,-9999.0
2015-04-05,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.01,-9999.0,-9999.0,-9999.0
2015-04-06,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,-9999.0,-9999.0
2015-04-07,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2015-04-08,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.03,-9999.0,-9999.0,-9999.0
2015-04-09,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.01,-9999.0,-9999.0,-9999.0
2015-04-10,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,-9999.0,-9999.0
2015-04-12,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.04,-9999.0,-9999.0,-9999.0
2015-04-13,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,-9999.0,-9999.0
2015-04-14,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.39,-9999.0,-9999.0,-9999.0
2015-04-15,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.01,-9999.0,-9999.0,-9999.0
2015-04-16,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2015-04-17,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2015-04-27,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,-9999.0,-9999.0
2015-04-28,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2015-04-29,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.09,-9999.0,-9999.0,-9999.0
2015-04-30,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.01,-9999.0,-9999.0,-9999.0
2015-05-01,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2015-05-02,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2015-05-03,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2015-05-04,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.00,-9999.0,0.0,-9999.0
2015-05-05,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.07,-9999.0,-9999.0,-9999.0
2015-05-06,GHCND:US1WAKG0188,SEATTLE 3.3 N WA US,0.44,-9999.0,-9999.0,-9999.0

In [34]:
NOAA.columns

Index(['STATION', 'STATION_NAME', 'Date', 'PRCP', 'SNWD', 'SNOW', 'WESF'], dtype='object')

In [35]:
NOAA_date_and_prcp = NOAA[['Date', 'PRCP']]

In [36]:
NOAA_date_and_prcp.set_index('Date')

            PRCP
Date
2013-01-01  0.00
2013-01-02  0.00
2013-01-03  0.00
2013-01-04  0.27
2013-01-05  0.00
2013-01-06  0.07
2013-01-07  0.07
2013-01-08  0.04
2013-01-09  0.84
2013-01-10  0.24
2013-01-11  0.04
2013-01-12  0.00
2013-01-13  0.00
2013-01-14  0.00
2013-01-15  0.00
2013-01-16  0.00
2013-01-17  0.00
2013-01-18  0.00
2013-01-19  0.00
2013-01-20  0.00
2013-01-21  0.00
2013-01-22  0.00
2013-01-23  0.00
2013-01-24  0.31
2013-01-25  0.19
2013-01-26  0.18
2013-01-27  0.09
2013-01-28  0.04
2013-01-29  0.33
2013-01-30  0.45
...          ...
2015-03-28  0.01
2015-03-29  0.00
2015-03-30  0.00
2015-03-31  0.06
2015-04-01  0.17
2015-04-02  0.19
2015-04-03  0.01
2015-04-04  0.02
2015-04-05  0.01
2015-04-06  0.00
2015-04-07  0.00
2015-04-08  0.03
2015-04-09  0.01
2015-04-10  0.00
2015-04-12  0.04
2015-04-13  0.00
2015-04-14  0.39
2015-04-15  0.01
2015-04-16  0.00
2015-04-17  0.00
2015-04-27  0.00
2015-04-28  0.00
2015-04-29  0.09
2015-04-30  0.01
2015-05-01  0.00
2015-05-02  0.00
2015-05-03  0.00
2015-05-04  0.00
2015-05-05  0.07
2015-05-06  0.44

[702 rows x 1 columns]

In [103]:
fremont_bike_count = pd.read_csv("fremont-bike-count.csv")

In [104]:
# fremont_bike_count.rename(columns={'Date': 'Date'}, inplace=True)

In [105]:
fremont_bike_count.columns

Index(['Date', 'Fremont Bridge West Sidewalk', 'Fremont Bridge East Sidewalk'], dtype='object')

In [106]:
number_of_nulls = fremont_bike_count.isnull().sum()  # Just for my info

In [107]:
#  I chose to fill the null fields with the median value

In [108]:
filled_fremont_bike_count = fremont_bike_count.fillna(fremont_bike_count[['Fremont Bridge East Sidewalk',
                                              'Fremont Bridge West Sidewalk']].median())

In [109]:
nulls_in_filled = filled_fremont_bike_count.isnull().sum()  # For my info

In [87]:
filled_fremont_bike_count.columns

Index(['Date', 'Fremont Bridge West Sidewalk', 'Fremont Bridge East Sidewalk'], dtype='object')

In [88]:
#  Now I need to aggregate the hours into days for the bridge data
filled_fremont_bike_count['Date'] = pd.to_datetime(filled_fremont_bike_count['Date'])

In [89]:
filled_fremont_bike_count.columns

Index(['Date', 'Fremont Bridge West Sidewalk', 'Fremont Bridge East Sidewalk'], dtype='object')

In [114]:
aggregated_bike_count = (filled_fremont_bike_count
.set_index(pd.DatetimeIndex(filled_fremont_bike_count['Date']))
.groupby(pd.TimeGrouper('D'))
.aggregate(np.sum)
.reset_index())

In [115]:
aggregated_bike_count.columns

Index(['Date', 'Fremont Bridge West Sidewalk', 'Fremont Bridge East Sidewalk'], dtype='object')

In [116]:
NOAA_date_and_prcp.columns

Index(['Date', 'PRCP'], dtype='object')

In [121]:
bridge_and_precip = aggregated_bike_count.merge(NOAA_date_and_prcp) # This took me forever to figure out

In [122]:
bridge_and_precip

,Date,Fremont Bridge West Sidewalk,Fremont Bridge East Sidewalk,PRCP
0,2013-01-01,344.0,334.0,0.00
1,2013-01-02,904.0,931.0,0.00
2,2013-01-03,890.0,913.0,0.00
3,2013-01-04,836.0,876.0,0.27
4,2013-01-05,403.0,316.0,0.00
5,2013-01-06,392.0,314.0,0.07
6,2013-01-07,968.0,925.0,0.07
7,2013-01-08,781.0,797.0,0.04
8,2013-01-09,697.0,650.0,0.84
9,2013-01-10,935.0,875.0,0.24
10,2013-01-11,804.0,766.0,0.04
11,2013-01-12,341.0,336.0,0.00
12,2013-01-13,335.0,224.0,0.00
13,2013-01-14,934.0,935.0,0.00
14,2013-01-15,1065.0,1001.0,0.00
15,2013-01-16,970.0,980.0,0.00
16,2013-01-17,883.0,894.0,0.00
17,2013-01-18,810.0,775.0,0.00
18,2013-01-19,421.0,339.0,0.00
19,2013-01-20,467.0,334.0,0.00
20,2013-01-21,644.0,632.0,0.00
21,2013-01-22,984.0,981.0,0.00
22,2013-01-23,896.0,871.0,0.00
23,2013-01-24,1003.0,952.0,0.31
24,2013-01-25,925.0,936.0,0.19
25,2013-01-26,286.0,258.0,0.18
26,2013-01-27,358.0,285.0,0.09
27,2013-01-28,877.0,831.0,0.04
28,2013-01-29,910.0,879.0,0.33
29,2013-01-30,873.0,887.0,0.45
...,...,...,...,...
672,2015-03-28,986.0,810.0,0.01
673,2015-03-29,842.0,566.0,0.00
674,2015-03-30,2014.0,1325.0,0.00
675,2015-03-31,563.0,1459.0,0.06
676,2015-04-01,730.0,1697.0,0.17
677,2015-04-02,1755.0,1073.0,0.19
678,2015-04-03,1331.0,1280.0,0.01
679,2015-04-04,1129.0,858.0,0.02
680,2015-04-05,934.0,795.0,0.01
681,2015-04-06,1731.0,1224.0,0.00
682,2015-04-07,1800.0,1248.0,0.00
683,2015-04-08,2077.0,1274.0,0.03
684,2015-04-09,1873.0,1797.0,0.01
685,2015-04-10,625.0,1594.0,0.00
686,2015-04-12,964.0,737.0,0.04
687,2015-04-13,1165.0,993.0,0.00
688,2015-04-14,1242.0,1182.0,0.39
689,2015-04-15,1908.0,1789.0,0.01
690,2015-04-16,2080.0,1922.0,0.00
691,2015-04-17,1815.0,1639.0,0.00
692,2015-04-27,2125.0,2015.0,0.00
693,2015-04-28,1405.0,1340.0,0.00
694,2015-04-29,1709.0,1728.0,0.09
695,2015-04-30,1794.0,1814.0,0.01
696,2015-05-01,2145.0,2079.0,0.00
697,2015-05-02,1209.0,1006.0,0.00
698,2015-05-03,1257.0,978.0,0.00
699,2015-05-04,2266.0,2254.0,0.00
700,2015-05-05,1323.0,1282.0,0.07
701,2015-05-06,2176.0,2055.0,0.44